# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
# If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.

image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS: "4333796"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./Group14/gradlew
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

#lintDebug:
#  stage: build
#  script:
#    - cd Group14/
#    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
#  tags:
#    - dalfcs_docker_autoscale

assembleDebug:
  stage: build
  script:
    - cd Group14/
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - Group14/app/build/outputs/
  tags:
    -  dalfcs_docker_autoscale

unit_tests:
  stage: test
  script:
    - cd Group14/
    - ./gradlew test
  artifacts:
    when: always
    expire_in: 4 days
    paths:
      - Group14/app/build/reports/tests/
  tags:
    -  dalfcs_docker_autoscale

debugTests:
  stage: test
  script:
    - cd Group14/
    - ./gradlew -Pci --console=plain :app:testDebug
  dependencies:
   - assembleDebug
  tags:
    -  dalfcs_docker_autoscale  
    